github.com:
    oauth_token: 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
    user: mr-hespicable
    git_protocol: ssh
    users:
        mr-hespicable:
            oauth_token: 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
